[build]
  base = "/"
  command = "npm install && cd client && npm install && npm run build"
  publish = "client/dist"

[dev]
  command = "cd client && npm run dev"
  port = 3000
  targetPort = 3000
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_URL = "https://pdfmaster.onrender.com"
  NODE_ENV = "production"
  
[functions]
  directory = "server/functions"
  node_bundler = "esbuild"
  
[functions.environment]
  VITE_API_URL = "https://pdfmaster.onrender.com"
  NODE_ENV = "production"

[functions.NPM_FLAGS]
  legacy_peer_deps = true

[context.production.environment]
  NODE_ENV = "production"
[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://pdfmaster.onrender.com;"
