services:
  - type: web
    name: pdfmaster-backend
    env: python
    region: singapore  # or choose a region closer to your users
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr
      pip install --upgrade pip
      pip install -r backend/requirements.txt
      pip install uvicorn gunicorn
    startCommand: |
      gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
    autoDeploy: true
    plan: free
    healthCheckPath: /docs
    instanceSize: free
    numInstances: 1
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
